OpenTSDB:
  url: http://opentsdb.net/
  description:  Classical time series database on top of HBase. Now support Cassandra and Bigtable.
  language: java
  backends:
    - HBase

KairosDB:
  url: https://kairosdb.github.io/
  description: Fast Time Series Database on Cassandra
  language: java
  backends:
    - Cassandra

Heroic:
  url: https://spotify.github.io/heroic/
  description: Scalable time series database based on Bigtable, Cassandra, and Elasticsearch
  language: java
  backends:
    - Cassandra
    - HBase
    - Bigtable
  links:
    "Monitoring at Spotify - Introducing Heroic": https://labs.spotify.com/2015/11/17/monitoring-at-spotify-introducing-heroic/

BTrDB:
  url: https://github.com/SoftwareDefinedBuildings/btrdb
  aka: Berkeley Tree Database
  description: High performance time series database designed to support high density data storage applications.
  language: Go
  backends:
    - Ceph
  links:
    "BTrDB: Optimizing Storage System Design for Timeseries Processing": https://www.usenix.org/system/files/conference/fast16/fast16-papers-andersen.pdf
